### ISSUE TITLE
How do I use with puppeteer?

### ISSUE THREAD

**Issue by jayzalowitz** [denene12/undetected-chrome-drive#2]

**Comment by okeanosthedev** [comment]
You actually don't need to use it with puppeteer. As puppeteer has its own system to bypass cloudflare this module does the same thing with the python module it uses in it, but if you tell me more or if there is anything incompatible of this module with puppeteer I can fix or as I said if you explain your need more I can code some example as you need.

**Comment by okeanosthedev** [comment]
Author of issue understood.
